// Generated by Wrangler by running `wrangler types`

interface Env {
	video_date_db: KVNamespace;
	article_summary: KVNamespace;
	DEEPFAKE_ID: "rdb0fe17e450";
	TAVUS_API_KEY: string;
	CHAT_API_KEY: string;
	THE_NEWS_API_KEY: string;
	video_storage: R2Bucket;
}
